### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by AhmedLotfy02** [abdelazizSalah/Azkark#5]
1. [x] **English-Arabic Switch**
2. [x] **Dark -Light Mode**
3. [x] **Azkar Frequency**

**Comment by abdelazizSalah** [comment]
6 hrs working on it

**Comment by abdelazizSalah** [comment]
work on Translation !

**Comment by AhmedLotfy02** [comment]
6 hrs 
All Except Duaa

**Comment by abdelazizSalah** [comment]
Done
